//! Build script — embed the built-in package std-lib into the binary.
//!
//! `temper`'s built-in packages live in a first-class `packages/<name>/PACKAGE.md`
//! tree at the repo root — *product* source, human-maintained from cited upstream
//! sources on the product's release cadence (`specs/10-contracts.md`, "Decision: a
//! package is project-authorable, not vendor-privileged — and is itself a kind":
//! the authoritative home is product territory, not the dogfood `.temper/`
//! workspace). This script walks that tree at compile time and generates a
//! `builtin_packages.rs` that embeds each `PACKAGE.md` verbatim via `include_str!`,
//! so the shipped binary carries the std-lib with no on-disk configuration and the
//! *same* document is authored as product source and shipped embedded — one
//! artifact, no `contracts/` mirror.
//!
//! The embed is auto-detected: every directory under `packages/` that carries a
//! `PACKAGE.md` is embedded, keyed by the directory name (`skill.anthropic`,
//! `rule.anthropic`, …). Adding a built-in package needs no edit here or to
//! `Cargo.toml` — drop a `packages/<name>/PACKAGE.md` and it ships. Keeping the
//! embed in the build script (not a `Cargo.toml` `include`) keeps it off the
//! manifest so it never collides with unrelated packaging metadata.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set by cargo");
    let packages_dir = Path::new(&manifest_dir).join("packages");

    // Re-run when a package is added, removed, or edited, so the embedded std-lib
    // never drifts from the authored source.
    println!("cargo:rerun-if-changed={}", packages_dir.display());

    let mut packages: Vec<(String, PathBuf)> = Vec::new();
    if let Ok(listing) = fs::read_dir(&packages_dir) {
        for entry in listing {
            let entry = entry.expect("reading a packages/ dir entry");
            let dir = entry.path();
            if !dir.is_dir() {
                continue;
            }
            let package_md = dir.join("PACKAGE.md");
            if !package_md.is_file() {
                continue;
            }
            let name = dir
                .file_name()
                .and_then(|stem| stem.to_str())
                .expect("a package directory name is valid UTF-8")
                .to_string();
            println!("cargo:rerun-if-changed={}", package_md.display());
            packages.push((name, package_md));
        }
    }
    // Sorted so the generated table (and every diagnostic ranging over it) is
    // stable across machines and runs.
    packages.sort();

    // Emit `BUILTIN_PACKAGES: &[(&str, &str)]` — each entry the package name paired
    // with its `PACKAGE.md` source, embedded byte-for-byte. Absolute paths so the
    // `include_str!` resolves regardless of where the generated file is included.
    let mut code = String::from(
        "/// Every embedded built-in package: `(name, PACKAGE.md source)`, sorted by\n\
         /// name. Generated by `build.rs` from the `packages/` product tree.\n\
         pub static BUILTIN_PACKAGES: &[(&str, &str)] = &[\n",
    );
    for (name, path) in &packages {
        let path = path
            .to_str()
            .expect("a package path under the manifest dir is valid UTF-8");
        writeln!(code, "    ({name:?}, include_str!({path:?})),").expect("writing to a String");
    }
    code.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is always set by cargo");
    let dest = Path::new(&out_dir).join("builtin_packages.rs");
    fs::write(&dest, code).expect("writing the generated builtin_packages.rs");
}
