/**
 * Byte-parity — the SDK emitter compiles to the exact inert manifest the Rust
 * `toml_edit` emitter produces (`specs/architecture/20-surface.md`,
 * "Content-faithful, deterministically emitted (law 5)"). Each fixture below is
 * **known-good Rust output**: it was generated by `write_manifest_members`
 * (`src/compose.rs`, the same path `temper emit` and `tests/genre_leaf.rs` /
 * `tests/emit.rs` cover) over the identical member, captured byte-for-byte. A
 * `serializeManifestMember` that diverges by one byte fails here — key order,
 * table-vs-header choice, string escaping (basic / literal / multiline), blank-
 * line placement, and array spelling all pinned.
 *
 * `String.raw` keeps backslashes in the fixtures literal (a TOML literal string
 * like `'path\to'` must not become a tab). Every fixture ends with a trailing
 * newline — `toml_edit` terminates the last value line.
 */

import assert from "node:assert/strict";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import {
  decision,
  defineHarness,
  emitManifestMembers,
  fromFile,
  md,
  rule,
  serializeManifestMember,
  toManifestMember,
} from "../src/index.js";
import type { ManifestMember } from "../src/index.js";

// ---------------------------------------------------------------------------
// The shared fixture corpus — one hand-built ManifestMember per fixture, paired
// with the byte-exact Rust emitter output for that same member.
// ---------------------------------------------------------------------------

/** A rule: a string-list field, a fill edge, headings, and a multiline body. */
const RULE_MEMBER: ManifestMember = {
  kind: "claude-code.rule",
  name: "rust",
  line_count: 3,
  headings: ["Rust conventions"],
  satisfies: ["engineering-standards"],
  fields: { paths: ["src/**/*.rs"] },
  sections: [
    {
      heading: "Rust conventions",
      body: "# Rust conventions\n\nErrors via miette/thiserror; clippy clean under -D warnings.",
    },
  ],
  genres: [],
  published: [],
};

const RULE_TOML = String.raw`[[member]]
kind = "claude-code.rule"
name = "rust"
line_count = 3
headings = ["Rust conventions"]
satisfies = ["engineering-standards"]

[member.field]
paths = ["src/**/*.rs"]

[[member.section]]
heading = "Rust conventions"
body = """
# Rust conventions

Errors via miette/thiserror; clippy clean under -D warnings."""
`;

/** A skill: a field whose value forces a multiline-basic string, plus a demand. */
const SKILL_MEMBER: ManifestMember = {
  kind: "claude-code.skill",
  name: "coordinate",
  line_count: 2,
  headings: ["Coordinate"],
  satisfies: [],
  fields: { description: 'Use when "coordinating" agents.\nSecond line.' },
  sections: [{ heading: "Coordinate", body: "Drive the team." }],
  genres: [],
  published: [{ name: "playbook", means: "a shared playbook exists", kind: "skill", required: true }],
};

const SKILL_TOML = String.raw`[[member]]
kind = "claude-code.skill"
name = "coordinate"
line_count = 2
headings = ["Coordinate"]

[member.field]
description = """
Use when "coordinating" agents.
Second line."""

[[member.section]]
heading = "Coordinate"
body = "Drive the team."

[[member.published]]
name = "playbook"
means = "a shared playbook exists"
kind = "skill"
required = true
`;

/** A decision genre value: flat leaves and a keyed sibling collection. */
const DECISION_MEMBER: ManifestMember = {
  kind: "decision",
  name: "05-surface-authority",
  line_count: 1,
  headings: [],
  satisfies: [],
  fields: {},
  sections: [],
  genres: [
    {
      genre: "decision",
      key: "surface-authority",
      leaves: {
        because: "law 7 needs an authored surface",
        chosen: "the composition surface is canonical",
      },
      collections: {
        rejected: { "baked-projection": { because: "a stamping projector breaks law 5" } },
      },
    },
  ],
  published: [],
};

const DECISION_TOML = String.raw`[[member]]
kind = "decision"
name = "05-surface-authority"
line_count = 1

[[member.genre]]
genre = "decision"
key = "surface-authority"

[member.genre.leaves]
because = "law 7 needs an authored surface"
chosen = "the composition surface is canonical"

[member.genre.collections]

[member.genre.collections.rejected]

[member.genre.collections.rejected.baked-projection]
because = "a stamping projector breaks law 5"
`;

/** A memory member: a boolean field, a backslash string (Rust picks a literal
 * string), and a genre with no collections. */
const MEMORY_MEMBER: ManifestMember = {
  kind: "claude-code.memory",
  name: "root",
  line_count: 5,
  headings: [],
  satisfies: [],
  fields: { "disable-model-invocation": true, note: "path\\to" },
  sections: [],
  genres: [{ genre: "bound", key: "reachability", leaves: { claim: "the world is a node" }, collections: {} }],
  published: [],
};

const MEMORY_TOML = String.raw`[[member]]
kind = "claude-code.memory"
name = "root"
line_count = 5

[member.field]
disable-model-invocation = true
note = 'path\to'

[[member.genre]]
genre = "bound"
key = "reachability"

[member.genre.leaves]
claim = "the world is a node"
`;

/** A decision whose `rejected` collection is declared but empty — the parent and
 * the collection header still emit, childless (the Rust `Table::new()` is not
 * implicit). */
const EMPTY_REJECTED_MEMBER: ManifestMember = {
  kind: "decision",
  name: "06-sole",
  line_count: 1,
  headings: [],
  satisfies: [],
  fields: {},
  sections: [],
  genres: [
    {
      genre: "decision",
      key: "sole",
      leaves: { chosen: "one option, no alternatives" },
      collections: { rejected: {} },
    },
  ],
  published: [],
};

const EMPTY_REJECTED_TOML = String.raw`[[member]]
kind = "decision"
name = "06-sole"
line_count = 1

[[member.genre]]
genre = "decision"
key = "sole"

[member.genre.leaves]
chosen = "one option, no alternatives"

[member.genre.collections]

[member.genre.collections.rejected]
`;

const CORPUS: readonly (readonly [string, ManifestMember, string])[] = [
  ["rule", RULE_MEMBER, RULE_TOML],
  ["skill", SKILL_MEMBER, SKILL_TOML],
  ["decision", DECISION_MEMBER, DECISION_TOML],
  ["memory", MEMORY_MEMBER, MEMORY_TOML],
  ["empty rejected collection", EMPTY_REJECTED_MEMBER, EMPTY_REJECTED_TOML],
];

for (const [label, member, expected] of CORPUS) {
  test(`byte-parity: ${label} serializes byte-identical to the Rust emitter`, () => {
    assert.equal(serializeManifestMember(member), expected);
  });

  test(`double-emit: ${label} is byte-stable`, () => {
    assert.equal(serializeManifestMember(member), serializeManifestMember(member));
  });
}

// The corpus, kind-then-name sorted exactly as `write_manifest_members` received
// it — byte-identical to the multi-member manifest root. The blank-line-before-
// every-header-but-the-first rule, verified across member boundaries.
const CORPUS_TOML = String.raw`[[member]]
kind = "claude-code.memory"
name = "root"
line_count = 5

[member.field]
disable-model-invocation = true
note = 'path\to'

[[member.genre]]
genre = "bound"
key = "reachability"

[member.genre.leaves]
claim = "the world is a node"

[[member]]
kind = "claude-code.rule"
name = "rust"
line_count = 3
headings = ["Rust conventions"]
satisfies = ["engineering-standards"]

[member.field]
paths = ["src/**/*.rs"]

[[member.section]]
heading = "Rust conventions"
body = """
# Rust conventions

Errors via miette/thiserror; clippy clean under -D warnings."""

[[member]]
kind = "claude-code.skill"
name = "coordinate"
line_count = 2
headings = ["Coordinate"]

[member.field]
description = """
Use when "coordinating" agents.
Second line."""

[[member.section]]
heading = "Coordinate"
body = "Drive the team."

[[member.published]]
name = "playbook"
means = "a shared playbook exists"
kind = "skill"
required = true

[[member]]
kind = "decision"
name = "05-surface-authority"
line_count = 1

[[member.genre]]
genre = "decision"
key = "surface-authority"

[member.genre.leaves]
because = "law 7 needs an authored surface"
chosen = "the composition surface is canonical"

[member.genre.collections]

[member.genre.collections.rejected]

[member.genre.collections.rejected.baked-projection]
because = "a stamping projector breaks law 5"

[[member]]
kind = "decision"
name = "06-sole"
line_count = 1

[[member.genre]]
genre = "decision"
key = "sole"

[member.genre.leaves]
chosen = "one option, no alternatives"

[member.genre.collections]

[member.genre.collections.rejected]
`;

test("byte-parity: the whole corpus matches the Rust multi-member manifest root", () => {
  // A member's block, standalone, has no leading blank; the document inserts one
  // blank line before every block but the first — so join-with-blank reconstructs
  // exactly what `write_manifest_members` emits over the sorted slice.
  const sorted = CORPUS.map(([, member]) => member).sort(
    (a, b) =>
      (a.kind < b.kind ? -1 : a.kind > b.kind ? 1 : 0) ||
      (a.name < b.name ? -1 : a.name > b.name ? 1 : 0),
  );
  assert.equal(sorted.map(serializeManifestMember).join("\n"), CORPUS_TOML);
});

// ---------------------------------------------------------------------------
// The authoring face end to end — emit sorts, maps every member through
// `toManifestMember`, and lands on the byte-parity serializer.
// ---------------------------------------------------------------------------

const surfaceAuthority = decision({
  key: "surface-authority",
  chosen: "the assembly declares the posture; enforcement reads it",
  rejected: {
    "baked-projection": { because: "bakes a stance law 2 says the author owns" },
  },
});

function harness() {
  return defineHarness({
    members: [
      rule({
        name: "rust",
        fields: { paths: ["src/**/*.rs"] },
        satisfies: {
          "engineering-standards": { rationale: "carries the Rust conventions" },
        },
        body: md`
          # Rust conventions

          Errors via miette/thiserror; clippy clean under -D warnings.
        `,
        genres: [surfaceAuthority],
      }),
    ],
  });
}

test("emit lands every member on the byte-parity serializer", () => {
  const toml = emitManifestMembers(harness());
  // The entry point equals the serializer over the same sorted, mapped members —
  // so the byte-parity the fixtures pin holds through `emit`, not just the seam.
  const sorted = [...harness().members]
    .sort(
      (a, b) =>
        (a.kind < b.kind ? -1 : a.kind > b.kind ? 1 : 0) ||
        (a.name < b.name ? -1 : a.name > b.name ? 1 : 0),
    )
    .map((member) => toManifestMember(member));
  assert.equal(toml, sorted.map(serializeManifestMember).join("\n"));
  // And it carries the expected schema.
  assert.match(toml, /^\[\[member\]\]$/m);
  assert.match(toml, /kind = "claude-code\.rule"/);
  assert.match(toml, /satisfies = \["engineering-standards"\]/);
  assert.match(toml, /^\[\[member\.section\]\]$/m);
  assert.match(toml, /^\[member\.genre\.collections\.rejected\.baked-projection\]$/m);
  assert.doesNotMatch(toml, /rejected\.0/);
});

test("double-emit over a harness is byte-stable", () => {
  assert.equal(emitManifestMembers(harness()), emitManifestMembers(harness()));
});

test("the leaf address rides structure: member + genre key + field path", () => {
  const manifest = toManifestMember(harness().members[0]);
  const value = manifest.genres[0];
  assert.equal(value.key, "surface-authority");
  assert.equal(value.collections.rejected["baked-projection"].because.length > 0, true);
});

// ---------------------------------------------------------------------------
// Body resolution — `fromFile` assets read in, mentions resolution-checked and
// rendered by the display rule (`specs/architecture/20-surface.md`, "Mentions").
// Resolution happens at emit against the whole harness's declared values.
// ---------------------------------------------------------------------------

test("a fromFile body resolves, emits, and stays byte-parity", () => {
  const dir = mkdtempSync(join(tmpdir(), "temper-fromfile-"));
  try {
    // A trailing newline forces the same multiline-basic spelling the Rust
    // emitter picks for an asset read from disk — the parity the fixture pins.
    const content = "# Long rule\n\nBody line one.\nBody line two.\n";
    writeFileSync(join(dir, "long.md"), content);
    const member = rule({ name: "long", body: fromFile("./long.md") });
    const harness = defineHarness({ members: [member] });

    const toml = emitManifestMembers(harness, { baseDir: dir });
    // The asset is the section body byte-for-byte — same bytes an inline member
    // carrying that content would land on the serializer.
    const expected: ManifestMember = {
      kind: "claude-code.rule",
      name: "long",
      line_count: content.split("\n").length,
      headings: ["Long rule"],
      satisfies: [],
      fields: {},
      sections: [{ heading: "Long rule", body: content }],
      genres: [],
      published: [],
    };
    assert.equal(toml, serializeManifestMember(expected));
    // Byte-deterministic: a second emit over the unchanged asset is identical.
    assert.equal(toml, emitManifestMembers(harness, { baseDir: dir }));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("a missing fromFile asset is a loud emit error", () => {
  const harness = defineHarness({
    members: [rule({ name: "long", body: fromFile("./absent.md") })],
  });
  assert.throws(() => emitManifestMembers(harness, { baseDir: tmpdir() }), /did not resolve/);
});

test("a resolved mention renders to its declared value's display form", () => {
  const target = rule({ name: "rust", body: md`# Rust` });
  const citer = rule({
    name: "citations",
    body: md`A ${{ address: "claude-code.rule:rust", display: "rust" }} is declared.`,
  });
  const harness = defineHarness({ members: [target, citer] });

  const toml = emitManifestMembers(harness);
  // The display rule substituted the target's form; the surrounding words and
  // spacing are the author's, and no interpolation marker survives (law 5).
  assert.match(toml, /body = "A rust is declared\."/);
  assert.doesNotMatch(toml, /\u0000/);

  // The rendered member is byte-identical to the same words authored inline.
  const rendered = serializeManifestMember(
    toManifestMember(citer, { mentionable: new Set(["claude-code.rule:rust"]) }),
  );
  const inline: ManifestMember = {
    kind: "claude-code.rule",
    name: "citations",
    line_count: 1,
    headings: [],
    satisfies: [],
    fields: {},
    sections: [{ heading: "citations", body: "A rust is declared." }],
    genres: [],
    published: [],
  };
  assert.equal(rendered, serializeManifestMember(inline));
  // Byte-deterministic across a second emit.
  assert.equal(toml, emitManifestMembers(harness));
});

test("an unresolved mention is a loud emit error", () => {
  const citer = rule({
    name: "citations",
    body: md`A ${{ address: "claude-code.rule:ghost", display: "ghost" }} is declared.`,
  });
  assert.throws(
    () => emitManifestMembers(defineHarness({ members: [citer] })),
    /a mention cannot dangle/,
  );
});
