//! The shared interchange corpus — the Rust side of `contract/`
//! (`specs/architecture/50-distribution.md`, "both implementations tested against one
//! golden set"). This suite is the **single producer** of the byte-parity manifest
//! goldens: it builds each member as a typed value, serializes it through the one Rust
//! emitter ([`temper::compose::manifest_members_to_string`]), and byte-matches the
//! result against the committed golden. The SDK's `emit.test.ts` reads the same files,
//! so a one-byte divergence in either serializer fails a suite.
//!
//! Two properties are pinned per golden: the emitter **produces** it (declare-side
//! integrity) and it **round-trips** (parse the golden back to members, re-serialize,
//! byte-identical) — so the write shape and the read shape are one. A third test pins
//! the Rust-first interchange schema + TS types generated by schemars/ts-rs.
//!
//! Regenerate every committed artifact after an intentional emitter change with
//! `BLESS=1 cargo test --test contract_fixtures` — a fixture edit is an
//! interface-version event (`.flume/chain.ts`, the `contract/**` fence note), so it is
//! never silent.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use temper::compose::{AuthorLayer, ManifestMember, manifest_members_to_string};
use temper::document::PublishedRequirement;
use temper::extract::{FeatureValue, Features, GenreValue, Kind, Section};
use temper::schema::interchange;

/// The `contract/` directory at the repository root — tests run with the crate root as
/// the working directory, so the goldens resolve relative to it.
fn contract_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("contract")
}

/// Whether this run should rewrite the committed artifacts rather than assert against
/// them — the `BLESS=1` regeneration mode (see the module header).
fn blessing() -> bool {
    std::env::var_os("BLESS").is_some()
}

/// Assert `actual` equals the committed golden at `contract/<rel>`, or — under `BLESS` —
/// (re)write the golden from `actual`, creating any parent directory. The one seam every
/// golden check goes through, so blessing and asserting stay in lock-step.
fn golden(rel: &str, actual: &str) {
    let path = contract_dir().join(rel);
    if blessing() {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("create contract subdir");
        }
        std::fs::write(&path, actual).expect("write golden");
        return;
    }
    let expected = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "read golden {}: {e} (run `BLESS=1` to generate)",
            path.display()
        )
    });
    assert_eq!(actual, expected, "golden mismatch at {}", path.display());
}

/// A scalar frontmatter feature of the given kind and text — the shape the extractor
/// yields and the manifest re-emits.
fn scalar(kind: Kind, text: &str) -> FeatureValue {
    FeatureValue::scalar(kind, text)
}

/// A minimal member skeleton: kind + id + line count, every optional facet empty. Each
/// fixture below fills only the facets it exercises, so the goldens stay terse.
fn member(kind: &str, id: &str, body_lines: usize) -> ManifestMember {
    ManifestMember {
        kind: kind.to_string(),
        features: Features {
            id: id.to_string(),
            fields: BTreeMap::new(),
            body_lines,
            headings: Vec::new(),
            sections: Vec::new(),
            source_dir: None,
            directives: Vec::new(),
            fenced_blocks: Vec::new(),
            genres: Vec::new(),
            satisfies: Vec::new(),
            published_requirements: Vec::new(),
        },
    }
}

/// A rule: a string-list field, a fill edge, headings, and a multiline body — the
/// [`RULE_MEMBER`](sdk/test/emit.test.ts) twin.
fn rule_member() -> ManifestMember {
    let mut m = member("claude-code.rule", "rust", 3);
    m.features.headings = vec!["Rust conventions".to_string()];
    m.features.satisfies = vec!["engineering-standards".to_string()];
    m.features.fields = BTreeMap::from([(
        "paths".to_string(),
        FeatureValue::List(vec!["src/**/*.rs".to_string()]),
    )]);
    m.features.sections = vec![Section {
        heading: "Rust conventions".to_string(),
        body: "# Rust conventions\n\nErrors via miette/thiserror; clippy clean under -D warnings."
            .to_string(),
    }];
    m
}

/// A skill: a field whose value forces a multiline-basic string, plus a published demand.
fn skill_member() -> ManifestMember {
    let mut m = member("claude-code.skill", "coordinate", 2);
    m.features.headings = vec!["Coordinate".to_string()];
    m.features.fields = BTreeMap::from([(
        "description".to_string(),
        scalar(
            Kind::String,
            "Use when \"coordinating\" agents.\nSecond line.",
        ),
    )]);
    m.features.sections = vec![Section {
        heading: "Coordinate".to_string(),
        body: "Drive the team.".to_string(),
    }];
    m.features.published_requirements = vec![PublishedRequirement {
        name: "playbook".to_string(),
        means: Some("a shared playbook exists".to_string()),
        kind: Some("skill".to_string()),
        package: None,
        required: true,
    }];
    m
}

/// A decision genre value: flat leaves and a keyed sibling collection.
fn decision_member() -> ManifestMember {
    let mut m = member("decision", "05-surface-authority", 1);
    m.features.genres = vec![GenreValue {
        genre: "decision".to_string(),
        key: "surface-authority".to_string(),
        leaves: BTreeMap::from([
            (
                "because".to_string(),
                "law 7 needs an authored surface".to_string(),
            ),
            (
                "chosen".to_string(),
                "the composition surface is canonical".to_string(),
            ),
        ]),
        collections: BTreeMap::from([(
            "rejected".to_string(),
            BTreeMap::from([(
                "baked-projection".to_string(),
                BTreeMap::from([(
                    "because".to_string(),
                    "a stamping projector breaks law 5".to_string(),
                )]),
            )]),
        )]),
    }];
    m
}

/// A memory member: a boolean field, a backslash string (a TOML literal string), and a
/// genre with no collections.
fn memory_member() -> ManifestMember {
    let mut m = member("claude-code.memory", "root", 5);
    m.features.fields = BTreeMap::from([
        (
            "disable-model-invocation".to_string(),
            scalar(Kind::Boolean, "true"),
        ),
        ("note".to_string(), scalar(Kind::String, "path\\to")),
    ]);
    m.features.genres = vec![GenreValue {
        genre: "bound".to_string(),
        key: "reachability".to_string(),
        leaves: BTreeMap::from([("claim".to_string(), "the world is a node".to_string())]),
        collections: BTreeMap::new(),
    }];
    m
}

/// A decision whose `rejected` collection is declared but empty — the parent and the
/// collection header still emit, childless.
fn empty_rejected_member() -> ManifestMember {
    let mut m = member("decision", "06-sole", 1);
    m.features.genres = vec![GenreValue {
        genre: "decision".to_string(),
        key: "sole".to_string(),
        leaves: BTreeMap::from([(
            "chosen".to_string(),
            "one option, no alternatives".to_string(),
        )]),
        collections: BTreeMap::from([("rejected".to_string(), BTreeMap::new())]),
    }];
    m
}

/// The corpus: each label paired with its member and the golden path under `contract/`.
fn corpus() -> Vec<(&'static str, ManifestMember, &'static str)> {
    vec![
        ("rule", rule_member(), "manifest/rule.toml"),
        ("skill", skill_member(), "manifest/skill.toml"),
        ("decision", decision_member(), "manifest/decision.toml"),
        ("memory", memory_member(), "manifest/memory.toml"),
        (
            "empty rejected collection",
            empty_rejected_member(),
            "manifest/empty-rejected.toml",
        ),
    ]
}

#[test]
fn each_member_serializes_byte_identical_to_its_golden() {
    for (label, member, rel) in corpus() {
        let emitted = manifest_members_to_string(std::slice::from_ref(&member));
        golden(rel, &emitted);
        // A standalone member block carries no leading blank — the byte form the SDK's
        // `serializeManifestMember` must match exactly (`emit.test.ts`).
        assert!(
            emitted.starts_with("[[member]]\n"),
            "{label}: a member block opens on `[[member]]`"
        );
    }
}

#[test]
fn the_whole_corpus_matches_the_multi_member_manifest_root() {
    // Kind-then-id sorted, exactly as `import`/`emit` hand `write_manifest_members` the
    // slice — the blank-line-before-every-header-but-the-first rule across boundaries.
    let mut members: Vec<ManifestMember> = corpus().into_iter().map(|(_, m, _)| m).collect();
    members.sort_by(|a, b| {
        a.kind
            .cmp(&b.kind)
            .then_with(|| a.features.id.cmp(&b.features.id))
    });
    let emitted = manifest_members_to_string(&members);
    golden("manifest/corpus.toml", &emitted);
}

#[test]
fn every_golden_round_trips_through_the_parser() {
    // The write shape and the read shape are one: parsing a golden back into members and
    // re-serializing yields the same bytes — so an extraction serialized into the manifest
    // reloads to the same features a live extraction produced. Skipped under `BLESS`, where
    // the goldens are being (re)written by a sibling test and may not yet exist on disk.
    if blessing() {
        return;
    }
    for (label, member, rel) in corpus() {
        let golden_text = std::fs::read_to_string(contract_dir().join(rel))
            .unwrap_or_else(|e| panic!("read {rel}: {e}"));
        let layer = AuthorLayer::parse(&golden_text, Path::new("temper.toml"))
            .unwrap_or_else(|e| panic!("{label}: parse golden: {e}"));
        assert_eq!(
            layer.members(),
            std::slice::from_ref(&member),
            "{label}: golden parses back to the source member"
        );
        assert_eq!(
            manifest_members_to_string(layer.members()),
            golden_text,
            "{label}: re-serializing the parsed golden is byte-identical"
        );
    }
}

#[test]
fn the_rust_first_interchange_schema_and_types_match_their_goldens() {
    // The JSON Schema (2020-12) and the TS type module generate Rust-first from the
    // manifest IR via schemars/ts-rs — the interchange contract both implementations
    // version against, checked in beside the byte goldens as one set.
    if blessing() {
        interchange::write_interchange(&contract_dir()).expect("write interchange artifacts");
    }
    golden(
        interchange::SCHEMA_JSON_PATH,
        &interchange::manifest_schema_json(),
    );
    golden(
        interchange::TYPES_TS_PATH,
        &interchange::manifest_types_ts(),
    );
}
