//! The seam bindings' staleness gate: a fresh `ts-rs` export of the TS↔Rust seam
//! family byte-compares against the committed `sdk/src/generated/` files. A
//! Rust-side row change with stale bindings fails here loudly (the fail-loud
//! invariant), never ships silent drift.
//!
//! The committed files are *generated*, never hand-edited: rerun this test with
//! `BLESS_SEAM_BINDINGS=1` to rewrite `sdk/src/generated/` from the current Rust
//! types, then commit the diff.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use ts_rs::{Config, TS};

use temper::drift::{
    AssemblyFactRow, BoundRow, CharsetRow, ClauseRow, CollectionAddressRow, CollectionEntryRow,
    CollectionEntryWire, CountBoundRow, Declarations, DegreeBoundRow, EdgeBoundRow, IncludeRow,
    KindFactRow, LayoutRegionRow, LayoutRow, MentionRow, NestedMemberRow, Payload, PayloadMember,
    RangeBoundRow, RegistrationRow, RequirementRow, SatisfiesRow, SectionContainsRow, SettingsRow,
};
use temper::extract::{
    EmbeddedMember, EmbeddedMemberCollectionEntry, FeatureValue, Features, FencedBlock, Section,
    ValueType,
};

/// The one binding home — the directory every seam type exports into.
fn generated_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("sdk/src/generated")
}

/// The export config the bindings ride: `.js` import specifiers, matching the
/// SDK's NodeNext ESM resolution (a generated cross-import is `./Other.js`).
fn config() -> Config {
    Config::default().with_import_extension(Some("js"))
}

/// The barrel's note — the generated `index.ts` is code's, never a hand edit.
const BARREL_NOTE: &str =
    "// This file re-exports the ts-rs seam bindings. Do not edit this file manually.\n";

/// One seam type's committed filename paired with its freshly-exported bytes.
fn binding<T: TS + 'static>(cfg: &Config) -> (String, String) {
    let path = <T as TS>::output_path()
        .expect("a seam binding type declares an output path")
        .to_string_lossy()
        .into_owned();
    let content =
        <T as TS>::export_to_string(cfg).expect("a seam binding type exports to a string");
    (path, content)
}

/// Every seam type's filename → freshly-exported bytes, plus the `index.ts`
/// barrel re-exporting each. The list is the whole TS↔Rust seam: the extraction
/// feature family and the payload/declaration-row family.
fn fresh_bindings() -> BTreeMap<String, String> {
    let cfg = config();
    let mut files = BTreeMap::new();

    macro_rules! collect {
        ($($ty:ty),* $(,)?) => {
            $(
                let (path, content) = binding::<$ty>(&cfg);
                files.insert(path, content);
            )*
        };
    }

    collect!(
        // Extraction feature family (`src/extract.rs`).
        ValueType,
        FeatureValue,
        Section,
        FencedBlock,
        EmbeddedMember,
        EmbeddedMemberCollectionEntry,
        Features,
        // Payload / declaration-row family (`src/drift.rs`).
        Payload,
        PayloadMember,
        Declarations,
        KindFactRow,
        CollectionAddressRow,
        LayoutRow,
        LayoutRegionRow,
        ClauseRow,
        BoundRow,
        CharsetRow,
        RangeBoundRow,
        SectionContainsRow,
        RequirementRow,
        CountBoundRow,
        DegreeBoundRow,
        EdgeBoundRow,
        SatisfiesRow,
        MentionRow,
        IncludeRow,
        NestedMemberRow,
        CollectionEntryRow,
        CollectionEntryWire,
        RegistrationRow,
        SettingsRow,
        AssemblyFactRow,
    );

    // The barrel re-exports each generated type, one `export type` per file, in
    // the same sorted order the map already keeps.
    let mut barrel = String::from(BARREL_NOTE);
    for path in files.keys() {
        let stem = path.trim_end_matches(".ts");
        barrel.push_str(&format!("export type {{ {stem} }} from \"./{stem}.js\";\n"));
    }
    files.insert("index.ts".to_owned(), barrel);
    files
}

/// The `.ts` files currently committed under the binding home.
fn committed_files(dir: &Path) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();
    let entries = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read the binding home `{}`: {e}", dir.display()));
    for entry in entries {
        let entry = entry.expect("a directory entry");
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.ends_with(".ts") {
            let content = std::fs::read_to_string(entry.path())
                .unwrap_or_else(|e| panic!("read `{name}`: {e}"));
            files.insert(name, content);
        }
    }
    files
}

#[test]
fn committed_bindings_byte_match_a_fresh_export() {
    let dir = generated_dir();
    let fresh = fresh_bindings();

    if std::env::var_os("BLESS_SEAM_BINDINGS").is_some() {
        std::fs::create_dir_all(&dir).expect("create the binding home");
        // Drop any committed `.ts` file the current type set no longer produces,
        // then write the fresh set — a retired type leaves no orphan behind.
        for name in committed_files(&dir).keys() {
            if !fresh.contains_key(name) {
                std::fs::remove_file(dir.join(name)).expect("remove a stale binding");
            }
        }
        for (name, content) in &fresh {
            std::fs::write(dir.join(name), content).expect("write a fresh binding");
        }
        return;
    }

    let committed = committed_files(&dir);

    let mut stale: Vec<String> = Vec::new();
    for (name, content) in &fresh {
        match committed.get(name) {
            Some(on_disk) if on_disk == content => {}
            Some(_) => stale.push(format!("`{name}` differs from a fresh export")),
            None => stale.push(format!("`{name}` is missing from the binding home")),
        }
    }
    for name in committed.keys() {
        if !fresh.contains_key(name) {
            stale.push(format!(
                "`{name}` is an orphan the current types no longer export"
            ));
        }
    }

    assert!(
        stale.is_empty(),
        "sdk/src/generated is stale — rerun with BLESS_SEAM_BINDINGS=1 to regenerate, then \
         commit the diff:\n  {}",
        stale.join("\n  "),
    );
}
