//! The seam bindings' staleness gate: a fresh export of the TS↔Rust seam family
//! byte-compares against the committed `sdk/src/generated/` files. A Rust-side change
//! with stale bindings fails here loudly (the fail-loud invariant), never ships silent
//! drift.
//!
//! The family is two things, not one: the `ts-rs` **types**, and the one module of
//! **values** — temper's gate commands, generated from the engine's own constants so a
//! scaffolded gate-hook member imports the binding instead of copying the bytes (0073).
//!
//! The committed files are *generated*, never hand-edited: rerun this test with
//! `BLESS_SEAM_BINDINGS=1` to rewrite `sdk/src/generated/` from the current Rust
//! sources, then commit the diff.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use ts_rs::{Config, TS};

use temper::compose::Verifier;
use temper::contract::Shape;
use temper::drift::{
    AssemblyFactRow, BoundRow, CharsetRow, ClauseRow, CollectionAddressRow, CollectionEntryRow,
    CollectionEntryWire, CountBoundRow, Declarations, DegreeBoundRow, EdgeBoundRow, IncludeRow,
    InputRow, KindFactRow, LayoutRegionRow, LayoutRow, MentionRow, NestedMemberRow, Payload,
    PayloadMember, RangeBoundRow, RegistrationRow, RequirementRow, SatisfiesRow,
    SectionContainsRow, SettingsRow, TemplateRow,
};
use temper::extract::{
    EmbeddedMember, EmbeddedMemberCollectionEntry, FeatureValue, Features, FencedBlock, Section,
    ValueType,
};
use temper::install::GATE_COMMAND_BINDINGS;

/// The one binding home — the directory every seam type exports into.
fn generated_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("sdk/src/generated")
}

/// The export config the bindings ride: `.js` import specifiers, matching the
/// SDK's NodeNext ESM resolution (a generated cross-import is `./Other.js`).
fn config() -> Config {
    Config::default().with_import_extension(Some("js"))
}

/// The barrel's note — the generated `index.ts` is code's, never a hand edit.
const BARREL_NOTE: &str =
    "// This file re-exports the generated seam bindings. Do not edit this file manually.\n";

/// The one generated file carrying **values** rather than a `ts-rs` type, so the barrel
/// re-exports it with `export { … }` and it is held out of the `export type` loop. Its
/// name is hyphen-cased on purpose: every sibling is a type file named for its type, and a
/// `gate-commands` stem cannot be mistaken for one.
const GATE_COMMANDS_FILE: &str = "gate-commands.ts";

/// The constants module's bytes: temper's gate commands, written from the engine's own
/// [`GATE_COMMAND_BINDINGS`] table — one home for the bytes and one for the names, so the
/// SDK copy is machine-written and this gate is what keeps it honest.
fn gate_commands_module() -> String {
    let mut src = String::from(
        "// This file carries temper's gate commands, generated from the engine's own \
         constants. Do not edit this file manually.\n",
    );
    for (binding, command) in GATE_COMMAND_BINDINGS {
        // JSON string encoding is TS string encoding for these bytes, and the commands
        // carry embedded quotes — so the escaping is `serde_json`'s, never hand-rolled.
        let literal = serde_json::to_string(command).expect("a command serializes infallibly");
        src.push_str(&format!("export const {binding} = {literal};\n"));
    }
    src
}

/// One seam type's committed filename paired with its freshly-exported bytes.
fn binding<T: TS + 'static>(cfg: &Config) -> (String, String) {
    let path = <T as TS>::output_path()
        .expect("a seam binding type declares an output path")
        .to_string_lossy()
        .into_owned();
    let content =
        <T as TS>::export_to_string(cfg).expect("a seam binding type exports to a string");
    (path, content)
}

/// Every generated file's name → its freshly-exported bytes, plus the `index.ts` barrel
/// re-exporting each. The list is the whole TS↔Rust seam: the extraction feature family,
/// the payload/declaration-row family, and the gate-command constants module.
fn fresh_bindings() -> BTreeMap<String, String> {
    let cfg = config();
    let mut files = BTreeMap::new();

    macro_rules! collect {
        ($($ty:ty),* $(,)?) => {
            $(
                let (path, content) = binding::<$ty>(&cfg);
                files.insert(path, content);
            )*
        };
    }

    collect!(
        // The clause vocabulary's own closed argument sets (`src/contract.rs`) — declared
        // once in Rust and generated across, so a member cannot be added on one side.
        Shape,
        // The requirement's typed verifier species union (`src/compose.rs`).
        Verifier,
        // Extraction feature family (`src/extract.rs`).
        ValueType,
        FeatureValue,
        Section,
        FencedBlock,
        EmbeddedMember,
        EmbeddedMemberCollectionEntry,
        Features,
        // Payload / declaration-row family (`src/drift.rs`).
        Payload,
        PayloadMember,
        Declarations,
        KindFactRow,
        TemplateRow,
        CollectionAddressRow,
        LayoutRow,
        LayoutRegionRow,
        ClauseRow,
        BoundRow,
        CharsetRow,
        RangeBoundRow,
        SectionContainsRow,
        RequirementRow,
        CountBoundRow,
        DegreeBoundRow,
        EdgeBoundRow,
        SatisfiesRow,
        MentionRow,
        IncludeRow,
        InputRow,
        NestedMemberRow,
        CollectionEntryRow,
        CollectionEntryWire,
        RegistrationRow,
        SettingsRow,
        AssemblyFactRow,
    );

    files.insert(GATE_COMMANDS_FILE.to_owned(), gate_commands_module());

    // The barrel re-exports each generated type, one `export type` per file, in the same
    // sorted order the map already keeps — then the constants module, whose exports are
    // values: a `export type { gate-commands }` line is neither its shape nor even TS, so
    // it is held out of the type loop and re-exported by name.
    let mut barrel = String::from(BARREL_NOTE);
    for path in files.keys().filter(|path| *path != GATE_COMMANDS_FILE) {
        let stem = path.trim_end_matches(".ts");
        barrel.push_str(&format!("export type {{ {stem} }} from \"./{stem}.js\";\n"));
    }
    let bindings: Vec<&str> = GATE_COMMAND_BINDINGS
        .iter()
        .map(|(binding, _)| *binding)
        .collect();
    let stem = GATE_COMMANDS_FILE.trim_end_matches(".ts");
    barrel.push_str(&format!(
        "export {{ {} }} from \"./{stem}.js\";\n",
        bindings.join(", ")
    ));
    files.insert("index.ts".to_owned(), barrel);
    files
}

/// The staleness readings between a fresh export and what is committed — one line per
/// disagreement, empty when the two sides are byte-equal. Factored out of the disk
/// comparison so the gate's own refusal is pinned over a hand-edited copy without ever
/// writing to the committed tree.
fn staleness(
    fresh: &BTreeMap<String, String>,
    committed: &BTreeMap<String, String>,
) -> Vec<String> {
    let mut stale: Vec<String> = Vec::new();
    for (name, content) in fresh {
        match committed.get(name) {
            Some(on_disk) if on_disk == content => {}
            Some(_) => stale.push(format!("`{name}` differs from a fresh export")),
            None => stale.push(format!("`{name}` is missing from the binding home")),
        }
    }
    for name in committed.keys() {
        if !fresh.contains_key(name) {
            stale.push(format!(
                "`{name}` is an orphan the current types no longer export"
            ));
        }
    }
    stale
}

/// The `.ts` files currently committed under the binding home.
fn committed_files(dir: &Path) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();
    let entries = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read the binding home `{}`: {e}", dir.display()));
    for entry in entries {
        let entry = entry.expect("a directory entry");
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.ends_with(".ts") {
            let content = std::fs::read_to_string(entry.path())
                .unwrap_or_else(|e| panic!("read `{name}`: {e}"));
            files.insert(name, content);
        }
    }
    files
}

#[test]
fn committed_bindings_byte_match_a_fresh_export() {
    let dir = generated_dir();
    let fresh = fresh_bindings();

    if std::env::var_os("BLESS_SEAM_BINDINGS").is_some() {
        std::fs::create_dir_all(&dir).expect("create the binding home");
        // Drop any committed `.ts` file the current type set no longer produces,
        // then write the fresh set — a retired type leaves no orphan behind.
        for name in committed_files(&dir).keys() {
            if !fresh.contains_key(name) {
                std::fs::remove_file(dir.join(name)).expect("remove a stale binding");
            }
        }
        for (name, content) in &fresh {
            std::fs::write(dir.join(name), content).expect("write a fresh binding");
        }
        return;
    }

    let committed = committed_files(&dir);
    // Vacuity pin: the whole generated family is under the compare, the constants module
    // included — a gate that judged an empty set would pass on anything.
    assert!(
        fresh.len() > 2 && fresh.contains_key(GATE_COMMANDS_FILE),
        "the fresh set is the whole seam family, got: {:?}",
        fresh.keys().collect::<Vec<_>>()
    );

    let stale = staleness(&fresh, &committed);
    assert!(
        stale.is_empty(),
        "sdk/src/generated is stale — rerun with BLESS_SEAM_BINDINGS=1 to regenerate, then \
         commit the diff:\n  {}",
        stale.join("\n  "),
    );
}

#[test]
fn a_hand_edited_constants_module_reads_stale_like_any_other_binding() {
    let fresh = fresh_bindings();
    let module = fresh
        .get(GATE_COMMANDS_FILE)
        .expect("the constants module joins the generated family");

    // Vacuity pin: the module names every binding and carries each command's own bytes,
    // so the refusal below is over the real generated content.
    for (binding, command) in GATE_COMMAND_BINDINGS {
        let literal = serde_json::to_string(command).unwrap();
        assert!(module.contains(binding), "got:\n{module}");
        assert!(module.contains(&literal), "got:\n{module}");
    }
    assert!(
        fresh["index.ts"].contains("export { GUARD_COMMAND, SESSION_START_COMMAND } from"),
        "the barrel re-exports the constants as values, got:\n{}",
        fresh["index.ts"]
    );

    // A hand edit to the generated bytes — the drift this gate exists to catch. It reads
    // exactly as a stale `ts-rs` binding does: same reading, same remedy.
    let mut edited = fresh.clone();
    edited.insert(
        GATE_COMMANDS_FILE.to_owned(),
        module.replace("temper guard .", "temper guard"),
    );
    assert_eq!(
        staleness(&fresh, &edited),
        vec![format!(
            "`{GATE_COMMANDS_FILE}` differs from a fresh export"
        )],
    );
}
